### ISSUE TITLE
cluster deployments not working

### ISSUE THREAD

**Issue by wrurik** [vdhicts/cyberfusion-cluster-api-client#19]
The `commit()` on the Clusters Endpoint has a wrong Url and body.

Url should be `cluster-deployments` and the `id` in the body should be `cluster_id`.

I tried creating a pull-request but I was not sure what to do with the response. 
As the response of this endpoint does not contain all properties to create a `new Cluster` from array.

**Comment by vdhicts** [comment]
Thank you for your feedback! 

I will fix the commit method to use the proper url and body. The response could still be a cluster object but I need to change the name to not be a required property.

**Comment by vdhicts** [comment]
This is solved in version 1.8.1. 

If you encounter any issues or questions, please feel free to open a new issue.
