### ISSUE TITLE
Feature request: add toggle for sandbox API

### ISSUE THREAD

**Issue by WilliamDEdwards** [vdhicts/cyberfusion-cluster-api-client#2]
If toggle is true, change `$url` default to `https://test-cluster-api.cyberfusion.nl/api/v1`.

**Comment by vdhicts** [comment]
Thanks you for submitting this issue.

I've included the sandbox mode in the latest release, version 1.1.0. See the [readme.md](https://github.com/vdhicts/cyberfusion-cluster-api-client/blob/main/README.md) how to enable/disable the sandbox mode.
