### ISSUE TITLE
Feature request: throw exception when health status is maintenance

### ISSUE THREAD

**Issue by WilliamDEdwards** [vdhicts/cyberfusion-cluster-api-client#3]
When health status is maintenance, API should not be used. Perhaps throw exception and do not execute API call when health status is maintenance.

**Comment by vdhicts** [comment]
Thank you for submitting this issue.

Do you want to health to be checked once or for every call?

**Comment by WilliamDEdwards** [comment]
> Do you want to health to be checked once or for every call?

I think customers of the Client class should not reuse the same object when the API is in `maintenance` mode, so perhaps health should be checked once, after which an immutable variable will be set preventing a class instance from being used as long as health was `maintenance` at least once.

**Comment by vdhicts** [comment]
Ok, will be looking to implement this.

**Comment by vdhicts** [comment]
Added in v1.2.0.
