### ISSUE TITLE
Support `certificates` PUT method

### ISSUE THREAD

**Issue by WilliamDEdwards** [vdhicts/cyberfusion-cluster-api-client#48]
## Goal

The `certificates` endpoint offers both PUT and PATCH methods. Currently, this client supports only the PATCH method. Please also support the PUT method.

## Additional information

The PATCH method is offered to avoid having to send the private key with every request. However, using the PUT method is necessary when having to replace both the certificate and the private key.

**Comment by vdhicts** [comment]
According to the documentation you can patch the key too. So is it really required to distinct the patch and put request in this package?

**Comment by WilliamDEdwards** [comment]
> According to the documentation you can patch the key too. So is it really required to distinguish the patch and put request in this package?

Technically, you're right: in practice, PUTting vs. PATCHing the `certificate` and `private_key` properties makes no difference. However, we can't guarantee PATCHes are impodent, which means that in theory the certificate and private key may not match, when committing one property succeeds but committing the other fails. In practice, this is very unlikely to happen, but we would like to do it by the book...

**Comment by vdhicts** [comment]
Ok, let me think about this. I might just add an extra method which requires all fields from the certificate model.
