### ISSUE TITLE
Improve the `ListFilter`

### ISSUE THREAD

**Issue by dvdheiden** [vdhicts/cyberfusion-cluster-api-client#61]
## Goal

- Improve the `ListFilter` which is updated to 1.78. 
- Think of way to prevent/notify about filtering on properties which aren't present.

## Additional information

> Not directly related, but FYI: we will be improving this behaviour in the API. key is currently searched for the literal value, which doesn't make too much sense when working with lists, because only the literal list, including all items in the list, is matched. However, we would expect filter to be mostly used to search for list items, instead of entire lists.
> 
> We will change/expand the behaviour of filter to either:
> 
> - Allow for searching for substring
> - Match literal list items aside from literal matching entire lists
> 
> Keep an eye out for the API changelog.

@wedwards wrote:

> This is fixed in API version 1.78! If key is a list, it will now be searched for an item containing the literal value. This replaces the old behaviour of literally matching the entire list. Version 1.78 will be released to the sandbox API today (yes, on a Friday, as the API is still in its early stages).

**Comment by dvdheiden** [comment]
I know, but it prevents mistakes. For example restarting the wrong FPM pool 🤣

**Comment by dvdheiden** [comment]
Already worked on this and will be finishing this soon. It will contain validation for the fields. Before being able to finish this, I need some more information about the way the filter works.

**Comment by WilliamDEdwards** [comment]
> > > Think of way to prevent/notify about filtering on properties which aren't present.
> > 
> > 
> > Note: using non-existent properties in filters doesn't cause errors. E.g. using the filter `thispropertydoesntexist:somevalue` wouldn't have any effect.
> 
> We are considering returning an error in the API when trying to filter on a key that doesn't exist. I will let you know if we go through with this ASAP.

Thank you. We've finalised the filter behaviour in 1.92.
