### ISSUE TITLE
MariaDB password hashing method for database user

### ISSUE THREAD

**Issue by mbardelmeijer** [vdhicts/cyberfusion-cluster-api-client#74]
## Goal

When setting the Database User's password, the `setPassword` method is available. The Cyberfusion API can accept a unencrypted password or a hashed password. The hashed variant must be generated with 'SHA-1 with PASSWORD()'. The hashed variant is deemed to be more secure, as no unhashed passwords are going via the API.

It would be nice if the library would have a method like `setHashedPassword` or `setPasswordAndHash` which runs it through this function before setting on the `DatabaseUser` model.

The following method can be used to generate it on PHP: `sprintf("*%s", strtoupper(sha1(sha1($password))))`

**Comment by dvdheiden** [comment]
Thanks for your feedback! 

I totally agree we should be working with encrypted passwords instead of plain text. That's why I'm considering to prevent sending an unencrypted password by always sending a hashed password. I will take a shot at it!

**Comment by dvdheiden** [comment]
Released in v1.33.0

**Comment by mbardelmeijer** [comment]
Thanks @dvdheiden! :)
