### ISSUE TITLE
VirtualHosts create and update endpoints do not send all available fields

### ISSUE THREAD

**Issue by WesleyKlop** [vdhicts/cyberfusion-cluster-api-client#86]
## Describe the bug

When using VirtualHosts::create or VirtualHosts::update, the body fields `allow_override_directives` and `allow_override_option_directives` are not included in the request body.

## Reproduction

1. Create a virtual host object containing either/both fields
2. Use the create or update method on `\Vdhicts\Cyberfusion\ClusterApi\Endpoints\VirtualHosts`
3. Validate neither fields are created or updated

## Expected behavior

That the fields `allow_override_directives` and `allow_override_option_directives` are set correctly

## Actual behavior

The fields  `allow_override_directives` and `allow_override_option_directives` are not set

**Comment by dvdheiden** [comment]
Fixed in v1.38.2
